# Generated by Django 2.1.8 on 2019-05-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190513_1529'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_genre',
            field=models.ManyToManyField(blank=True, related_name='like_people', to='movies.Genre'),
        ),
    ]
