# Generated by Django 2.1.8 on 2019-05-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_like_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_genre',
        ),
    ]
