# Generated by Django 2.1.8 on 2019-05-09 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('en_title', models.CharField(max_length=150)),
                ('open_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('imageurl', models.CharField(max_length=150)),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.Actor')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
                ('scores', models.ManyToManyField(related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
