# Generated by Django 2.1.8 on 2019-05-13 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20190513_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='like_people',
            field=models.ManyToManyField(blank=True, related_name='like_genre', to=settings.AUTH_USER_MODEL),
        ),
    ]
