# Generated by Django 2.1.8 on 2019-05-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_genre_like_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='like_people',
        ),
    ]
