# Generated by Django 2.1.8 on 2019-05-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_genre_like_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='hashtags', to='movies.Movie')),
            ],
        ),
    ]
