# Generated by Django 2.1.8 on 2019-05-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Hashtag'),
        ),
    ]
